@startuml

!includeurl https://raw.githubusercontent.com/jurgenei/generate-plantuml-action/master/example/ing.iuml!0
[First component]
[Another component] as Comp2  
component Comp3
component [Last\ncomponent] as Comp4

@enduml